version: 2

models:
  - name: my_python_model
    config:
      materialized: table
      tags: ['python']
      columns:
        - name: id
          tests:
            - unique
            - not_null
